### ISSUE TITLE
Handle system light/dark mode settings

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#58]
Observed on macOS, may apply to Windows as well?

System dark mode settings apparently apply to parts of apps by default. Opening InVEST with dark mode results in a black background with white text. It's alright but not aesthetically nice as the light mode version. The only real problem is that the log text ends up being invisible (black on black). It shouldn't be too hard to set a complementary dark mode color scheme.

**Comment by davemfish** [comment]
For the time being, and for our immediate milestone of distributing this app internaly, I think we could resolve this by forcing light mode on all OS. I think that should be possible with the electron API https://www.electronjs.org/docs/api/native-theme#nativethemethemesource

Later on we could certainly design a dark mode if that's an important feature. 

@emlys would you like to take this issue since you have a Mac to test on?

**Comment by emlys** [comment]
Sure! I agree that forcing light mode is the best solution for now
